version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 200000000stake
- name: bob
  coins:
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
- name: validator1
  bonded: 100000000stake
- name: validator2
  bonded: 200000000stake
- name: validator3
  bonded: 300000000stake
genesis:
  app_state:
    swap:
      params:
       swap_rules:
        - src_denom: stake
          dst_denom: stake1
          ratio: "0.50"
          min_supply_ratio_limit: "0.6667"
        - src_denom: stake1
          dst_denom: stake
          ratio: "0.80"
          min_supply_ratio_limit: "0.3333"