// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package swap

import (
	v1beta1 "cosmossdk.io/api/cosmos/base/v1beta1"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_PartialSend               protoreflect.MessageDescriptor
	fd_PartialSend_id            protoreflect.FieldDescriptor
	fd_PartialSend_recipient     protoreflect.FieldDescriptor
	fd_PartialSend_burntAmount   protoreflect.FieldDescriptor
	fd_PartialSend_sentAmount    protoreflect.FieldDescriptor
	fd_PartialSend_swappedAmount protoreflect.FieldDescriptor
	fd_PartialSend_creator       protoreflect.FieldDescriptor
)

func init() {
	file_magicswap_swap_partial_send_proto_init()
	md_PartialSend = File_magicswap_swap_partial_send_proto.Messages().ByName("PartialSend")
	fd_PartialSend_id = md_PartialSend.Fields().ByName("id")
	fd_PartialSend_recipient = md_PartialSend.Fields().ByName("recipient")
	fd_PartialSend_burntAmount = md_PartialSend.Fields().ByName("burntAmount")
	fd_PartialSend_sentAmount = md_PartialSend.Fields().ByName("sentAmount")
	fd_PartialSend_swappedAmount = md_PartialSend.Fields().ByName("swappedAmount")
	fd_PartialSend_creator = md_PartialSend.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_PartialSend)(nil)

type fastReflection_PartialSend PartialSend

func (x *PartialSend) ProtoReflect() protoreflect.Message {
	return (*fastReflection_PartialSend)(x)
}

func (x *PartialSend) slowProtoReflect() protoreflect.Message {
	mi := &file_magicswap_swap_partial_send_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_PartialSend_messageType fastReflection_PartialSend_messageType
var _ protoreflect.MessageType = fastReflection_PartialSend_messageType{}

type fastReflection_PartialSend_messageType struct{}

func (x fastReflection_PartialSend_messageType) Zero() protoreflect.Message {
	return (*fastReflection_PartialSend)(nil)
}
func (x fastReflection_PartialSend_messageType) New() protoreflect.Message {
	return new(fastReflection_PartialSend)
}
func (x fastReflection_PartialSend_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_PartialSend
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_PartialSend) Descriptor() protoreflect.MessageDescriptor {
	return md_PartialSend
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_PartialSend) Type() protoreflect.MessageType {
	return _fastReflection_PartialSend_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_PartialSend) New() protoreflect.Message {
	return new(fastReflection_PartialSend)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_PartialSend) Interface() protoreflect.ProtoMessage {
	return (*PartialSend)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_PartialSend) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_PartialSend_id, value) {
			return
		}
	}
	if x.Recipient != "" {
		value := protoreflect.ValueOfString(x.Recipient)
		if !f(fd_PartialSend_recipient, value) {
			return
		}
	}
	if x.BurntAmount != nil {
		value := protoreflect.ValueOfMessage(x.BurntAmount.ProtoReflect())
		if !f(fd_PartialSend_burntAmount, value) {
			return
		}
	}
	if x.SentAmount != nil {
		value := protoreflect.ValueOfMessage(x.SentAmount.ProtoReflect())
		if !f(fd_PartialSend_sentAmount, value) {
			return
		}
	}
	if x.SwappedAmount != nil {
		value := protoreflect.ValueOfMessage(x.SwappedAmount.ProtoReflect())
		if !f(fd_PartialSend_swappedAmount, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_PartialSend_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_PartialSend) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "magicswap.swap.PartialSend.id":
		return x.Id != uint64(0)
	case "magicswap.swap.PartialSend.recipient":
		return x.Recipient != ""
	case "magicswap.swap.PartialSend.burntAmount":
		return x.BurntAmount != nil
	case "magicswap.swap.PartialSend.sentAmount":
		return x.SentAmount != nil
	case "magicswap.swap.PartialSend.swappedAmount":
		return x.SwappedAmount != nil
	case "magicswap.swap.PartialSend.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: magicswap.swap.PartialSend"))
		}
		panic(fmt.Errorf("message magicswap.swap.PartialSend does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PartialSend) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "magicswap.swap.PartialSend.id":
		x.Id = uint64(0)
	case "magicswap.swap.PartialSend.recipient":
		x.Recipient = ""
	case "magicswap.swap.PartialSend.burntAmount":
		x.BurntAmount = nil
	case "magicswap.swap.PartialSend.sentAmount":
		x.SentAmount = nil
	case "magicswap.swap.PartialSend.swappedAmount":
		x.SwappedAmount = nil
	case "magicswap.swap.PartialSend.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: magicswap.swap.PartialSend"))
		}
		panic(fmt.Errorf("message magicswap.swap.PartialSend does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_PartialSend) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "magicswap.swap.PartialSend.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	case "magicswap.swap.PartialSend.recipient":
		value := x.Recipient
		return protoreflect.ValueOfString(value)
	case "magicswap.swap.PartialSend.burntAmount":
		value := x.BurntAmount
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "magicswap.swap.PartialSend.sentAmount":
		value := x.SentAmount
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "magicswap.swap.PartialSend.swappedAmount":
		value := x.SwappedAmount
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "magicswap.swap.PartialSend.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: magicswap.swap.PartialSend"))
		}
		panic(fmt.Errorf("message magicswap.swap.PartialSend does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PartialSend) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "magicswap.swap.PartialSend.id":
		x.Id = value.Uint()
	case "magicswap.swap.PartialSend.recipient":
		x.Recipient = value.Interface().(string)
	case "magicswap.swap.PartialSend.burntAmount":
		x.BurntAmount = value.Message().Interface().(*v1beta1.Coin)
	case "magicswap.swap.PartialSend.sentAmount":
		x.SentAmount = value.Message().Interface().(*v1beta1.Coin)
	case "magicswap.swap.PartialSend.swappedAmount":
		x.SwappedAmount = value.Message().Interface().(*v1beta1.Coin)
	case "magicswap.swap.PartialSend.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: magicswap.swap.PartialSend"))
		}
		panic(fmt.Errorf("message magicswap.swap.PartialSend does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PartialSend) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "magicswap.swap.PartialSend.burntAmount":
		if x.BurntAmount == nil {
			x.BurntAmount = new(v1beta1.Coin)
		}
		return protoreflect.ValueOfMessage(x.BurntAmount.ProtoReflect())
	case "magicswap.swap.PartialSend.sentAmount":
		if x.SentAmount == nil {
			x.SentAmount = new(v1beta1.Coin)
		}
		return protoreflect.ValueOfMessage(x.SentAmount.ProtoReflect())
	case "magicswap.swap.PartialSend.swappedAmount":
		if x.SwappedAmount == nil {
			x.SwappedAmount = new(v1beta1.Coin)
		}
		return protoreflect.ValueOfMessage(x.SwappedAmount.ProtoReflect())
	case "magicswap.swap.PartialSend.id":
		panic(fmt.Errorf("field id of message magicswap.swap.PartialSend is not mutable"))
	case "magicswap.swap.PartialSend.recipient":
		panic(fmt.Errorf("field recipient of message magicswap.swap.PartialSend is not mutable"))
	case "magicswap.swap.PartialSend.creator":
		panic(fmt.Errorf("field creator of message magicswap.swap.PartialSend is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: magicswap.swap.PartialSend"))
		}
		panic(fmt.Errorf("message magicswap.swap.PartialSend does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_PartialSend) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "magicswap.swap.PartialSend.id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "magicswap.swap.PartialSend.recipient":
		return protoreflect.ValueOfString("")
	case "magicswap.swap.PartialSend.burntAmount":
		m := new(v1beta1.Coin)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "magicswap.swap.PartialSend.sentAmount":
		m := new(v1beta1.Coin)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "magicswap.swap.PartialSend.swappedAmount":
		m := new(v1beta1.Coin)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "magicswap.swap.PartialSend.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: magicswap.swap.PartialSend"))
		}
		panic(fmt.Errorf("message magicswap.swap.PartialSend does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_PartialSend) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in magicswap.swap.PartialSend", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_PartialSend) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PartialSend) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_PartialSend) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_PartialSend) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*PartialSend)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		l = len(x.Recipient)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.BurntAmount != nil {
			l = options.Size(x.BurntAmount)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.SentAmount != nil {
			l = options.Size(x.SentAmount)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.SwappedAmount != nil {
			l = options.Size(x.SwappedAmount)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*PartialSend)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x32
		}
		if x.SwappedAmount != nil {
			encoded, err := options.Marshal(x.SwappedAmount)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x2a
		}
		if x.SentAmount != nil {
			encoded, err := options.Marshal(x.SentAmount)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x22
		}
		if x.BurntAmount != nil {
			encoded, err := options.Marshal(x.BurntAmount)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Recipient) > 0 {
			i -= len(x.Recipient)
			copy(dAtA[i:], x.Recipient)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Recipient)))
			i--
			dAtA[i] = 0x12
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*PartialSend)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PartialSend: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PartialSend: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Recipient = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BurntAmount", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.BurntAmount == nil {
					x.BurntAmount = &v1beta1.Coin{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.BurntAmount); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SentAmount", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.SentAmount == nil {
					x.SentAmount = &v1beta1.Coin{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.SentAmount); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SwappedAmount", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.SwappedAmount == nil {
					x.SwappedAmount = &v1beta1.Coin{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.SwappedAmount); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: magicswap/swap/partial_send.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartialSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Recipient     string        `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	BurntAmount   *v1beta1.Coin `protobuf:"bytes,3,opt,name=burntAmount,proto3" json:"burntAmount,omitempty"`
	SentAmount    *v1beta1.Coin `protobuf:"bytes,4,opt,name=sentAmount,proto3" json:"sentAmount,omitempty"`
	SwappedAmount *v1beta1.Coin `protobuf:"bytes,5,opt,name=swappedAmount,proto3" json:"swappedAmount,omitempty"`
	Creator       string        `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *PartialSend) Reset() {
	*x = PartialSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magicswap_swap_partial_send_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartialSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialSend) ProtoMessage() {}

// Deprecated: Use PartialSend.ProtoReflect.Descriptor instead.
func (*PartialSend) Descriptor() ([]byte, []int) {
	return file_magicswap_swap_partial_send_proto_rawDescGZIP(), []int{0}
}

func (x *PartialSend) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PartialSend) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *PartialSend) GetBurntAmount() *v1beta1.Coin {
	if x != nil {
		return x.BurntAmount
	}
	return nil
}

func (x *PartialSend) GetSentAmount() *v1beta1.Coin {
	if x != nil {
		return x.SentAmount
	}
	return nil
}

func (x *PartialSend) GetSwappedAmount() *v1beta1.Coin {
	if x != nil {
		return x.SwappedAmount
	}
	return nil
}

func (x *PartialSend) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_magicswap_swap_partial_send_proto protoreflect.FileDescriptor

var file_magicswap_swap_partial_send_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x73, 0x77, 0x61, 0x70,
	0x2f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x73,
	0x77, 0x61, 0x70, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x63,
	0x6f, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x02, 0x0a, 0x0b, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x0b, 0x62, 0x75, 0x72, 0x6e, 0x74,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x0b, 0x62,
	0x75, 0x72, 0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x0a, 0x73, 0x65,
	0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52,
	0x0a, 0x73, 0x65, 0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x0d, 0x73,
	0x77, 0x61, 0x70, 0x70, 0x65, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x42, 0x04, 0xc8,
	0xde, 0x1f, 0x00, 0x52, 0x0d, 0x73, 0x77, 0x61, 0x70, 0x70, 0x65, 0x64, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42, 0xb2, 0x01, 0x0a,
	0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x73,
	0x77, 0x61, 0x70, 0x42, 0x10, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x6e, 0x64,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x78, 0x43, 0x6f, 0x72, 0x70, 0x69, 0x30, 0x78, 0x2f, 0x6d, 0x61,
	0x67, 0x69, 0x63, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x67, 0x69,
	0x63, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x73, 0x77, 0x61, 0x70, 0xa2, 0x02, 0x03, 0x4d, 0x53, 0x58,
	0xaa, 0x02, 0x0e, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x53, 0x77, 0x61,
	0x70, 0xca, 0x02, 0x0e, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x73, 0x77, 0x61, 0x70, 0x5c, 0x53, 0x77,
	0x61, 0x70, 0xe2, 0x02, 0x1a, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x73, 0x77, 0x61, 0x70, 0x5c, 0x53,
	0x77, 0x61, 0x70, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x0f, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x73, 0x77, 0x61, 0x70, 0x3a, 0x3a, 0x53, 0x77, 0x61,
	0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_magicswap_swap_partial_send_proto_rawDescOnce sync.Once
	file_magicswap_swap_partial_send_proto_rawDescData = file_magicswap_swap_partial_send_proto_rawDesc
)

func file_magicswap_swap_partial_send_proto_rawDescGZIP() []byte {
	file_magicswap_swap_partial_send_proto_rawDescOnce.Do(func() {
		file_magicswap_swap_partial_send_proto_rawDescData = protoimpl.X.CompressGZIP(file_magicswap_swap_partial_send_proto_rawDescData)
	})
	return file_magicswap_swap_partial_send_proto_rawDescData
}

var file_magicswap_swap_partial_send_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_magicswap_swap_partial_send_proto_goTypes = []interface{}{
	(*PartialSend)(nil),  // 0: magicswap.swap.PartialSend
	(*v1beta1.Coin)(nil), // 1: cosmos.base.v1beta1.Coin
}
var file_magicswap_swap_partial_send_proto_depIdxs = []int32{
	1, // 0: magicswap.swap.PartialSend.burntAmount:type_name -> cosmos.base.v1beta1.Coin
	1, // 1: magicswap.swap.PartialSend.sentAmount:type_name -> cosmos.base.v1beta1.Coin
	1, // 2: magicswap.swap.PartialSend.swappedAmount:type_name -> cosmos.base.v1beta1.Coin
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_magicswap_swap_partial_send_proto_init() }
func file_magicswap_swap_partial_send_proto_init() {
	if File_magicswap_swap_partial_send_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_magicswap_swap_partial_send_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartialSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_magicswap_swap_partial_send_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_magicswap_swap_partial_send_proto_goTypes,
		DependencyIndexes: file_magicswap_swap_partial_send_proto_depIdxs,
		MessageInfos:      file_magicswap_swap_partial_send_proto_msgTypes,
	}.Build()
	File_magicswap_swap_partial_send_proto = out.File
	file_magicswap_swap_partial_send_proto_rawDesc = nil
	file_magicswap_swap_partial_send_proto_goTypes = nil
	file_magicswap_swap_partial_send_proto_depIdxs = nil
}
